import type { MetadataRoute } from "next";

/**
 * robots.txt — generated by Next.js so it sits at /robots.txt.
 * Tells crawlers what they're welcome to index. We expose every public
 * marketing page but explicitly block the authenticated member area,
 * the admin panel, the API routes, and the personal `payment/` flow.
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: ["/"],
        disallow: [
          "/admin",
          "/admin/",
          "/api/",
          "/dashboard",
          "/profile",
          "/profile/",
          "/coaching",
          "/coaching/",
          "/jobs",
          "/jobs/",
          "/courses",
          "/skills",
          "/skills/",
          "/network",
          "/notifications",
          "/notifications/",
          "/tools",
          "/tools/",
          "/billing",
          "/billing/",
          "/payment/",
          "/progress",
          "/progress/",
          "/recruiters",
          "/koral-connections",
          "/community",
          "/events",
          "/updates",
          "/updates/",
          "/guide",
          "/reset-password/",
        ],
      },
    ],
    sitemap: "https://app.careerinfocus.co.il/sitemap.xml",
    host: "https://app.careerinfocus.co.il",
  };
}
