import type { MetadataRoute } from "next";

/**
 * sitemap.xml — generated by Next.js so it sits at /sitemap.xml.
 * Lists every page we want indexed. Authenticated routes stay out;
 * Google has no business listing /dashboard or /profile.
 *
 * We add freshness hints (priority + changeFrequency) calibrated to how
 * often each page actually changes — the landing page updates with each
 * marketing pass, terms/privacy rarely. lastModified is "now" so a fresh
 * deploy invalidates the cache the crawler holds.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const base = "https://app.careerinfocus.co.il";
  const now = new Date();

  return [
    {
      url: `${base}/`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 1.0,
    },
    {
      url: `${base}/pricing`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      // Lead magnet — high priority for SEO since it's the page we
      // want to rank for "בדיקת התאמה לעבודה" searches.
      url: `${base}/cv-match`,
      lastModified: now,
      changeFrequency: "weekly",
      priority: 0.95,
    },
    {
      url: `${base}/login`,
      lastModified: now,
      changeFrequency: "yearly",
      priority: 0.7,
    },
    {
      url: `${base}/signup`,
      lastModified: now,
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: `${base}/about`,
      lastModified: now,
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${base}/contact`,
      lastModified: now,
      changeFrequency: "yearly",
      priority: 0.6,
    },
    {
      url: `${base}/accessibility`,
      lastModified: now,
      changeFrequency: "yearly",
      priority: 0.4,
    },
    {
      url: `${base}/privacy`,
      lastModified: now,
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: `${base}/terms`,
      lastModified: now,
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: `${base}/forgot-password`,
      lastModified: now,
      changeFrequency: "yearly",
      priority: 0.3,
    },
  ];
}
